name: Build goiftop

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'


      - name: 安装依赖库
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-libc-dev libpcap-dev libnetfilter-queue-dev libnetfilter-log-dev
          
      - name: 克隆 goiftop 仓库
        run: |
          git clone --depth=1 https://github.com/84896150/goiftop.git
          ls -l
          
      - name: 编译项目
        run: |
          cd goiftop
          make build-armv7
          ls -l
          pwd

      - name : Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Frp-packages
          path: /home/runner/work/goiftop/goiftop/bin/
      
